### PR TITLE
Fixes #27

### LINKED ISSUE #27: Dataset download does not work in Pytorch 2.0+
Trying to download a dataset for the first time in PyTorch 2.1.2 I get:

```
  File "AudioLoader/speech/speechcommands.py", line 238, in __init__
    download_url(url, root, hash_value=checksum, hash_type="md5")
TypeError: download_url_to_file() got an unexpected keyword argument 'hash_value'
```

Looking at the documentation, the function does appear to be missing those parameters:
https://pytorch.org/docs/1.13/hub.html#torch.hub.download_url_to_file

### PR DESCRIPTION
**Pull request by V0XNIHILI**
Since downloading the dataset doesn't work correctly anymore, use the original dataset from PyTorch Audio directly to download the data while keeping the rest of the code the same.

### CODE REVIEW

**Comment by KinWaiCheuk** [comment]
LGTM
