### ISSUE TITLE
Dataset download does not work in Pytorch 2.0+

### ISSUE THREAD

**Issue by fayalalebrun** [KinWaiCheuk/AudioLoader#27]
Trying to download a dataset for the first time in PyTorch 2.1.2 I get:

```
  File "AudioLoader/speech/speechcommands.py", line 238, in __init__
    download_url(url, root, hash_value=checksum, hash_type="md5")
TypeError: download_url_to_file() got an unexpected keyword argument 'hash_value'
```

Looking at the documentation, the function does appear to be missing those parameters:
https://pytorch.org/docs/1.13/hub.html#torch.hub.download_url_to_file

**Comment by fayalalebrun** [comment]
Aside from the download_url_to_file` API changing, the `_export_zip` function now used in place of `export_archive` does not support `.tar.gz` files.

**Comment by Vosatorp** [comment]
Hi! Have you figured out how to fix the problem? How can I download MAESTRO, MAPS or MusicNet datasets?

**Comment by V0XNIHILI** [comment]
I opened a PR for solving this issue with SpeechCommands at least: #29
